export const mockProducts = [
  'Ergonomic Office Chair',
  'Non-Stick Frying Pan Set',
  'Latest Model Smartphone',
  'Wireless Headphones',
  '4K Television',
  'Robot Vacuum Cleaner',
  'Gaming Console',
  'Gaming Laptop',
  'Smartwatch',
  'Espresso Coffee Machine',
  'Fitness Tracker',
  'Electric Toothbrush',
  'Microwave Oven',
  'Refrigerator with Freezer Compartment',
  'Dishwasher',
  'Action Camera',
  'Drawing Tablet',
  'Electric Scooter',
  'External Hard Drive',
  'Bluetooth Speaker',
  'Adjustable Desk Lamp',
  'Vintage Jeans',
  "Women's Coat",
  "Men's Sneakers",
  "Children's Toy Set",
  'Bestselling Book',
  'E-Reader',
  'Photo Printer',
  'Smart Bulb',
  'Home Projector',
  'Barbecue Grill Set',
  'Garden Tools',
  'Blender Mixer',
  'Washing Machine',
  'Neck and Back Massager',
  'Board Game',
  'Exercise Bike',
  'Yoga Mat',
  'Electric Hoverboard',
  'Kitchen Processor',
  'Bed Linen Set',
  'Lighted Mirror',
  'Air Humidifier',
  'Oven',
  'Tablet Computer',
  'Smart Thermostat',
  'Electric Stove',
  'Hair Dryer',
  'PC Video Game',
  '3D Printer',
  'Camera Drone',
  'Tool Set',
  'Laptop Bag',
  'Travel Backpack',
  'Cosmetics Set',
  'Perfume',
  'LED Light Strips',
  'Acoustic System',
  'Thermos',
  'Pot Set',
  'Electric Kettle',
  'Fitness Equipment',
  'Portable Charger',
  'Smart Speaker',
  'Quadcopter',
  'Digital Thermometer',
  'Manicure Set',
  '2000W Vacuum Cleaner',
  'Gaming Monitor',
  'VR Headset',
  'Baby Stroller',
  'Car GPS Navigator',
  'Electronic Lock',
  'Cutlery Set',
  'Kitchen Knife Block',
  'Electric Drill',
  'Wet and Dry Robot Vacuum',
  'Smart Door Lock',
  'Car Dash Cam',
  'Barista Kit',
  'Garden Furniture',
  'Digital Photo Frame',
  'Mini Cookie Oven',
  "Children's Playground Set",
  'Smart Bracelet with GPS',
  'Picnic Set',
  'Wireless Charging Pad',
  'Smart Alarm Clock',
  'Folding Bicycle',
  'Embroidery Kit',
  'Electric Skateboard',
  'Square Headphones',
  'Multifunctional Knife',
  'Smartphone Accessories Set',
  'Portable Projector',
  'Barbecue Tool Set',
  'Fitness Tracker with Heart Rate Monitor',
  'Electronic Dental Floss',
  'Smart Bicycle Lock',
  "Children's Tablet",
  'Surge Protector with Overvoltage Protection',
  'Sushi Making Kit',
] as const;
