import type { Metadata } from 'next';
import cl from 'classnames';
import { Inter } from 'next/font/google';

import { AppLayout } from '@/common/layouts/AppLayout';
import { AppProvider } from '@/common/AppProvider';

import { AppPublicIcons } from '@/common/AppPublicIcons';
import '@/styles/globals.scss';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: AppPublicIcons.icon(),
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full" lang="en">
      <body className={cl('h-full relative overflow-hidden', inter.className)}>
        <AppProvider>
          <AppLayout>{children}</AppLayout>
        </AppProvider>
      </body>
    </html>
  );
}
